### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by MaaniBeigy** [artmarydotir/aasaam-static#1]
Hi @artmarydotir,
would you please add RTL support for the markdown files generated in Farsi?  :pray:
Thanks a lot  :heart_eyes:

**Comment by artmarydotir** [comment]
Hi, thank you for your contribution and interest in improving aasaam static project.
But we're a very small development team, and we cant add any new feature,
If you can improve anything in this repo, feel free to add a pull request @MaaniBeigy :blush:

**Comment by MaaniBeigy** [comment]
Ok :neutral_face: thanks @artmarydotir

**Comment by artmarydotir** [comment]
RTL support added.
